# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-07 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0003_auto_20190404_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalwebsite',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
