# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-09 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0005_auto_20190409_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalwebsite',
            name='image',
            field=models.ImageField(blank=True, default='profile_image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='personalwebsite',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
