# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-09 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0008_personalwebsite_education_masters_details_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalwebsite',
            name='education_other',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='education_other_details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
