# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-09 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0010_auto_20190409_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalwebsite',
            name='about_title_four',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='about_title_one',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='about_title_three',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='about_title_two',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
