# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0011_auto_20190409_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_details',
            new_name='skills_details_five',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_title',
            new_name='skills_title_five',
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='skills_details_four',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='skills_details_one',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='skills_details_six',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='skills_details_three',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='skills_details_two',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='skills_title_four',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='skills_title_one',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='skills_title_six',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='skills_title_three',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='skills_title_two',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
