# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-09 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0012_auto_20190409_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='services_details',
            new_name='services_details_five',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_details_five',
            new_name='services_details_four',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_details_four',
            new_name='services_details_one',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_details_one',
            new_name='services_details_six',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_details_six',
            new_name='services_details_three',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_details_three',
            new_name='services_details_two',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='services_title',
            new_name='services_title_five',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_title_five',
            new_name='services_title_four',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_title_four',
            new_name='services_title_one',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_title_one',
            new_name='services_title_six',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_title_six',
            new_name='services_title_three',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_title_three',
            new_name='services_title_two',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_details_two',
            new_name='skills_details',
        ),
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='skills_title_two',
            new_name='skills_title',
        ),
    ]
