# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0013_auto_20190409_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalwebsite',
            name='work_image_five',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='work_image_four',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='work_image_one',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='work_image_six',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='work_image_three',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='work_image_two',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
