# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-09 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0016_auto_20190409_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalwebsite',
            name='recent_work_four',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='personalwebsite',
            name='recent_work_one',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='personalwebsite',
            name='recent_work_three',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='personalwebsite',
            name='recent_work_two',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
