# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0021_auto_20190418_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_small_title', models.CharField(blank=True, max_length=2000, null=True)),
                ('blog_title', models.CharField(blank=True, max_length=2000, null=True)),
                ('blog_text', models.TextField(blank=True, max_length=2000, null=True)),
                ('blog_images', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_small_title', models.CharField(blank=True, max_length=2000, null=True)),
                ('blog_title', models.CharField(blank=True, max_length=2000, null=True)),
                ('blog_text', models.TextField(blank=True, max_length=2000, null=True)),
                ('blog_images', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
