# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-18 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0022_post_three_post_two'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_three',
            old_name='blog_images',
            new_name='blog_images_three',
        ),
        migrations.RenameField(
            model_name='post_three',
            old_name='blog_small_title',
            new_name='blog_small_title_three',
        ),
        migrations.RenameField(
            model_name='post_three',
            old_name='blog_text',
            new_name='blog_text_three',
        ),
        migrations.RenameField(
            model_name='post_three',
            old_name='blog_title',
            new_name='blog_title_three',
        ),
        migrations.RenameField(
            model_name='post_three',
            old_name='created_date',
            new_name='created_date_three',
        ),
        migrations.RenameField(
            model_name='post_three',
            old_name='published_date',
            new_name='published_date_three',
        ),
        migrations.RenameField(
            model_name='post_two',
            old_name='blog_images',
            new_name='blog_images_two',
        ),
        migrations.RenameField(
            model_name='post_two',
            old_name='blog_small_title',
            new_name='blog_small_title_two',
        ),
        migrations.RenameField(
            model_name='post_two',
            old_name='blog_text',
            new_name='blog_text_two',
        ),
        migrations.RenameField(
            model_name='post_two',
            old_name='blog_title',
            new_name='blog_title_two',
        ),
        migrations.RenameField(
            model_name='post_two',
            old_name='created_date',
            new_name='created_date_two',
        ),
        migrations.RenameField(
            model_name='post_two',
            old_name='published_date',
            new_name='published_date_two',
        ),
    ]
