# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0025_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recentwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_work_one', models.CharField(blank=True, max_length=2000, null=True)),
                ('recent_work_two', models.CharField(blank=True, max_length=2000, null=True)),
                ('recent_work_three', models.CharField(blank=True, max_length=2000, null=True)),
                ('recent_work_four', models.CharField(blank=True, max_length=2000, null=True)),
                ('work_image_one', models.ImageField(blank=True, default='', upload_to='')),
                ('work_image_two', models.ImageField(blank=True, default='', upload_to='')),
                ('work_image_three', models.ImageField(blank=True, default='', upload_to='')),
                ('work_image_four', models.ImageField(blank=True, default='', upload_to='')),
                ('work_image_five', models.ImageField(blank=True, default='', upload_to='')),
                ('work_image_six', models.ImageField(blank=True, default='', upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='recent_work_four',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='recent_work_one',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='recent_work_three',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='recent_work_two',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='work_image_five',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='work_image_four',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='work_image_one',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='work_image_six',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='work_image_three',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='work_image_two',
        ),
    ]
