# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-21 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0026_auto_20190421_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(blank=True, max_length=2000, null=True)),
                ('gallery_text', models.TextField(blank=True, max_length=2000, null=True)),
                ('gallery_images', models.ImageField(upload_to='')),
                ('gallery_date', models.DateTimeField(auto_now_add=True)),
                ('gallery_published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
