# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-29 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0029_auto_20190423_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_title', models.CharField(blank=True, max_length=2000, null=True)),
                ('skills_details', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='skills_details',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='skills_title',
        ),
    ]
