# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-29 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0030_auto_20190429_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title_one', models.CharField(blank=True, max_length=2000, null=True)),
                ('services_details_one', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='education_bachelor',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='education_bachelor_details',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='education_college',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='education_college_details',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='education_other',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='education_other_details',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='education_school',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='education_school_details',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='services_details_five',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='services_details_four',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='services_details_one',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='services_details_six',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='services_details_three',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='services_details_two',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='services_title_five',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='services_title_four',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='services_title_one',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='services_title_six',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='services_title_three',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='services_title_two',
        ),
    ]
