# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-29 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0031_auto_20190429_0652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostThree',
        ),
        migrations.DeleteModel(
            name='PostTwo',
        ),
    ]
