# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-29 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0032_auto_20190429_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experience_details_five',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_details_four',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_details_six',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_details_three',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_details_two',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_title_five',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_title_four',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_title_six',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_title_three',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_title_two',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_years_five',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_years_four',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_years_six',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_years_three',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_years_two',
        ),
    ]
