# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-29 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0033_auto_20190429_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentwork',
            name='recent_work_four',
        ),
        migrations.RemoveField(
            model_name='recentwork',
            name='recent_work_three',
        ),
        migrations.RemoveField(
            model_name='recentwork',
            name='recent_work_two',
        ),
        migrations.RemoveField(
            model_name='recentwork',
            name='work_image_five',
        ),
        migrations.RemoveField(
            model_name='recentwork',
            name='work_image_four',
        ),
        migrations.RemoveField(
            model_name='recentwork',
            name='work_image_six',
        ),
        migrations.RemoveField(
            model_name='recentwork',
            name='work_image_three',
        ),
        migrations.RemoveField(
            model_name='recentwork',
            name='work_image_two',
        ),
    ]
