# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-29 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0034_auto_20190429_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_title_one', models.CharField(blank=True, max_length=2000, null=True)),
                ('client_title_two', models.CharField(blank=True, max_length=2000, null=True)),
                ('client_title_three', models.CharField(blank=True, max_length=2000, null=True)),
                ('client_title_four', models.CharField(blank=True, max_length=2000, null=True)),
                ('client_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
