# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-29 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0036_auto_20190429_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bg_image',
        ),
    ]
