# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-29 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0037_remove_client_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalwebsite',
            name='projects_done',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='projects_done_number',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
